// Generated by CoffeeScript 1.11.1

/*
@fileOverview ./index.coffee
@description
Grammuelle.
 */

(function() {
  var Grammuelle, Operation, Parser, _, __fs__, __q__, capture_module, g, log, open;

  __fs__ = require('fs');

  __q__ = require('promise-defer');

  log = console.log;

  _ = require('lodash');

  String.prototype.int = function() {
    return parseInt(this, 10);
  };


  /*
  @name open
  @description
  Open a stylebook.
   */

  open = function(f) {
    var defer;
    if (f == null) {
      f = './__test__.scss';
    }
    defer = __q__();
    __fs__.readFile(f, 'utf-8', function(error, data) {
      defer.resolve(data);
    });
    return defer.promise;
  };


  /*
  @name capture_module
  @description
  Look for Do(...)
   */

  capture_module = function(view) {
    var m;
    if (m = view.match(/(\@include\s*(.*)\(\')(.*)(\')/)) {
      view = ("module[" + m.index + "]__") + m[3];
    }
    return view;
  };


  /*
  @class
  @name Parser
  @description
  Parser Contract Loader.
   */

  Parser = (function() {
    function Parser(parsers) {
      this.parsers = parsers;
    }

    Parser.prototype.contract = function(loaded, parser) {
      if (parser) {
        return parser(loaded || '');
      } else {
        return loaded;
      }
    };

    Parser.prototype.parse = function(content) {
      var c, list, view;
      c = content.split("\n");
      return list = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = c.length; j < len; j++) {
          view = c[j];
          results.push(this.ready(view));
        }
        return results;
      }).call(this);
    };

    Parser.prototype.ready = function(view) {
      var p;
      return p = this.parsers.reduce(this.contract, view);
    };

    return Parser;

  })();


  /*
  @class
  @name Operation
   */

  Operation = (function() {
    function Operation(op) {
      this.op = op;
      this.op;
    }

    return Operation;

  })();


  /*
  @class
  @name Grammuelle
   */

  Grammuelle = (function() {
    var p;

    p = new Parser([capture_module]);

    function Grammuelle() {
      this.schema = null;
      this.schemas = [];
      this.done = null;
      open('./stylebook.grams').then(function(data) {
        return this.schema = data;
      });
    }

    Grammuelle.prototype.generate = function() {
      var d;
      d = __q__();
      open().then(function(data) {
        var parseMap, psb;
        psb = p.parse(data);
        parseMap = _.filter(_.map(psb, function(d) {
          var c, capitalizedFirstCharOfName, classPosition, dirtyName, firstCharRemoved, h, newComponentName, newModuleName, opname, privateClassPosition;
          opname = null;
          if (c = d.match(/module\[([0-9])\]\_\_(.*)/)) {
            h = c[1].int();
            classPosition = 0;
            privateClassPosition = 2;
            dirtyName = c[2];
            if (h === classPosition && dirtyName) {
              capitalizedFirstCharOfName = dirtyName.split('').reverse().pop().toUpperCase();
              firstCharRemoved = dirtyName.slice(1, dirtyName.length);
              newModuleName = capitalizedFirstCharOfName + firstCharRemoved;
              opname = newModuleName;
            }
            if (h === privateClassPosition && dirtyName) {
              newComponentName = dirtyName.toLowerCase();
              opname = newComponentName;
            }
          }
          return opname;
        }));
        _.each(parseMap, function(q, i) {
          var INIT, INIT_SCOPE, INNER, INNER_SCOPE, NAME, NAME_SCOPE, capitalizedFirstCharOfName, firstCharRemoved, init, inner, named, newPrivateClassName;
          NAME = /%%SCSS_NAME%%/;
          NAME_SCOPE = /%%SCSS_NAME%%/g;
          INNER = /%%SCSS_INNER%%/;
          INNER_SCOPE = /%%SCSS_INNER%%/g;
          INIT = /%%SCSS_INIT_INNER%%/;
          INIT_SCOPE = /%%SCSS_INIT_INNER%%/g;
          inner = this.schema.match(INNER);
          init = this.schema.match(INIT);
          named = this.schema.match(NAME);
          if (named) {
            this.schema = this.schema.replace(NAME_SCOPE, q);
            return this.filename = q;
          } else if (inner || init) {
            if (inner) {
              capitalizedFirstCharOfName = q.split('').reverse().pop().toUpperCase();
              firstCharRemoved = q.slice(1, q.length);
              newPrivateClassName = capitalizedFirstCharOfName + firstCharRemoved;
              this.schema = this.schema.replace(INNER_SCOPE, newPrivateClassName);
            }
            return this.schema = this.schema.replace(INIT_SCOPE, q);
          }
        });
        return d.resolve({
          schema: this.schema,
          filename: this.filename
        });
      });
      return d.promise;
    };

    return Grammuelle;

  })();

  g = new Grammuelle;

  g.generate().then(function(output) {
    var ext, filepath, inputdata, pathbase;
    pathbase = './';
    ext = '.coffee';
    filepath = pathbase + output.filename + ext;
    inputdata = output.schema;
    return __fs__.writeFile(filepath, inputdata, (function(_this) {
      return function(error) {
        if (error != null) {
          return log(error);
        } else {
          return log("Saved " + output.filename);
        }
      };
    })(this));
  });

}).call(this);
