// Generated by CoffeeScript 1.11.1
(function() {
  var ModelP;

  ModelP = (function() {
    var Header;

    Header = (function() {
      function Header() {}

      return Header;

    })();

    function ModelP() {
      this.render();
    }

    ModelP.prototype.render = function() {
      this.header = new Header;
    };

    return ModelP;

  })();

  module.exports = ModelP;

}).call(this);
